baseURL = ""
relativeURLs = "True"
languageCode = 'en-us'
title = 'Deja Cherese'

[taxonomies]
    category = "categories"
    author = "authors"
    tag = "tags"
    includes = "includes"

[markup.goldmark.renderer]
  unsafe = true

