baseURL = 'https://lustrous-cranachan-1952e1.netlify.app/'
languageCode = 'en-us'
title = 'Deja Cherese'

[taxonomies]
    category = "categories"
    author = "authors"
    tag = "tags"
    includes = "includes"

