[context.production.environment]
	HUGO_VERSION = "0.121.1"
	HUGO_ENV = "production"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.121.1"

[build]
	publish = "public"
	command = "hugo --minify --buildFuture"